### ISSUE TITLE
Backend config

### ISSUE THREAD

**Issue by bas24** [swissup/module-countdowntimer#4]
Hello,
Could you explain please what I need to change in backend to show countdown at product page?
Thank you in advance

**Comment by tangar76** [comment]
Please use widget interfaces in Magento Admin.
![image](https://user-images.githubusercontent.com/13131588/87907890-1eca2900-ca6e-11ea-94c4-3067a240c57f.png)

**Comment by bas24** [comment]
Thank you.
One more question: strange things, running first time that was countdown but after reaching 00 00 00 it becomes countup :-) recreating widget not lead  to any difference. What I can check/update/flush more?

**Comment by tangar76** [comment]
Yep there was a bug with counting up.
It is fixed now. Please update module.
