### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by amenk** [swissup/module-countdowntimer#6]
Thanks for the nice module.

If possible, we could add screenshots to the readme.

Does it look similar to https://docs.swissuplabs.com/m1/extensions/countdowntimer/ ?

**Comment by tangar76** [comment]
It is one of the most challenging tasks :monocle_face: :smile: 
And we finally completed it :tada: 

https://docs.swissuplabs.com/m2/extensions/countdown-timer/

Thank you for patience.
